//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReview.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Review
    {
        public Review()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }

        public string UserName { get; set; }

        [Required]
        public int RestaurantId { get; set; }

        [Required]
        [Range(0.0, 10.0, ErrorMessage = "Ratings must be between 0.0 and 10.0")]
        public decimal Rating { get; set; }

        [Required]
        public string Content { get; set; }

        public System.DateTime Timestamp { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }

        public virtual Restaurant Restaurant { get; set; }
    }
}
